language: php
php:
  - 5.3
  - 5.4

env:
  - NO_INTERACTION=1

before_script:
  - sh -c "cd vendor/libcld2/internal && sh compile_libs.sh"
  - sh -c "phpize"
  - sh -c "./configure --with-libcld-dir=vendor/libcld2"
  - sh -c "make"

script:
  - make test
  - cat tests/*.diff || true

notifications:
  email:
    - lstrojny@php.net
